server:
  port: 8090
spring:
  application:
    name: resource-server
  datasource:
    url: jdbc:mysql://localhost:3306/resource_service
    username: root
    password: kishor@2233#
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000