server:
  port: 9000

spring:
  application:
    name: auth-server
  datasource:
    url: jdbc:mysql://localhost:3306/springSecurityClient
    username: root
    password: kishor@2233#
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update