server:
  port: 8080

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/springSecurityClient
    username: root
    password: kishor@2233#
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
          user-service-oidc:
            provider: spring
            client-id: user-service
            client-secret: user123
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
            scope: openid
            client-name: user-service-oidc
          user-service-authorization-code:
            provider: spring
            client-id: user-service
            client-secret: user123
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/authorized"
            scope: message.read
            client-name: user-service-authorization-code
        provider:
          spring:
            issuer-uri: http://localhost:9000